### ISSUE TITLE
User edit/delete

### ISSUE THREAD

**Issue by christopherConcannon** [christopherConcannon/instartist#5]
* implement functionality for user to update or delete their user profile
* add buttons for each behavior to user dashboard
* edit button will load edit-user page which displays form to invoke PUT /api/users/:id route on submit
* delete button will hit DELETE /api/users/:id -- need to add front end delete-user.js to dashboard.handlebars which will add 
     event listener to delete button which calls function to make delete fetch request to route
* all associated comments and posts should be removed
* verify session destroyed and logged out
* redirect to homepage

**Comment by anniavd** [comment]
The user is only allowed to edit the extra data (biography, media, interests). When the user is deleted, everything associated with it is deleted.

**Comment by christopherConcannon** [comment]
when the user info is updated, the app should redirect to the dashboard populated by the updated info

**Comment by anniavd** [comment]
ready
